
public enum ContextType {

	RESTAURANTS,BASEBALL,IVY_LEAGUE,
	
	EXPLANATION, GREETING, LISA, CONVERSE, UNIVERSE, AGREEMENT, DISAGREEMENT, GRUMP, DENY_ANTECENDENT,

	BALLSINABUCKET, NUMBER, INTRO, RIGHT, WRONG, Accused_Murder, Body_Politics, Voting, Empty, ONE, BALLET, BAD_STUNTS, CARS, BEST_OF_FIVE, HOSPITALS, WORD_COUNT, MIXED, SLOTTING, UNIVERSITIES, IMPERFECTIONS, GLOBOMA, CAB, POLICE_DOG, STORM, COIN_TOSS, SLOT_GAMBLER, COIN_GAME, LOTTERY, ROULETTE, SUBWAY, BOARD_GAME, RAVENCLAW, GREEN_OUTFITS, PAY_TV, BORING_CINEMA, BORING_AUNT, THEATRE_TICKET, SPORTS_TICKET, POPCORN, UNIVERSITY_RENOVATION, TUNA_SANDWICH, WARDROBE, SOFTWARE_PROJECT, TEACHING_METHOD, PENNIES, MARBLE_TRAY, THEATRE, OUTCOME1A, OUTCOME1B, CONTEXT, OUTCOME2A, OUTCOME2B, OUTCOME3B, OUTCOME3, OUTCOME3A, SYLLOG1, SYLLOG2, SYLLOG3, SYLLOG4, SYLLOG5, SYLLOG6, SYLLOG7, SYLLOG8, SYLLOG9, DRUG, BACK_PAIN, GRADES, PARROTS, GLASSES, TOMATO, VOWELEVENNUMBER, BOARD_GAME_DEVELOPMENT, CAT_FLU, WEDDING_CARDS, TOWELS, BIRDS, CLARIFICATION, CAPTCHA, HUMAN_HELP, WANT_RATIONAL, GUT, HUMAN, NAME, UNSURE, SPEED, LIKE, TEST, ANY_QUESTIONS, SURE, BREAST_CANCER, GOON, NOTHING	
	
	
	
	// old content, delete?
	/*
	s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s19, s18,
	BALLSINABUCKET,
	TERRORISTSCAN,
	BRUSTKREBS,
	EIER,
	ALEX,
	FAMILY_GAME,
	SUSAN,
	LINDA,
	SEQUENCE_DICES,
	SEQUENCE_FLIPS,
	MALE_BABIES,
	ELECTRIC_SHOCK,
	DNA_SAMPLE,
	RISKY_GAMES,
	CARL,
	FLAPEMIA,
	RAINY_DAYS,
	SUNSHINE,
	GRAVITY,
	STAR_WARS,
	CLOTHING_VOUCHER,
	MONEY_IN_A_YEAR,
	PRESENTATION_PREPARATION,
	PENS_FOR_A_MUG,
	MP3_PLAYER,
	LONGEVITY_AND_FUN,
	LAZY_GOVERNMENT,
	SMOKING_KILLS,
	ALIENS,
	CHANGE
	*/

}
