
public enum InputType {
	NO_IDEA, NO_INPUT, CORRECT, INCORRECT, INPUT_FAULT, NO_GENERAL, BORING, COOL, ABORT, NO_CLUE,
	CONTINUE, SMALL, MEDIUM,LARGE, WHY, ABOUT_YOU, YES_NO, QUESTION, HATE, LOVE, PURPOSE, ANSWER1, ANSWER2, HOW, OK, BAD, INTERESTING, ASK_FOR_PERCENT, HOW_ARE, WAIT, HINT, EXPLAIN, THANKYOU, FASTER, SLOWER, REQUEST_STORY, SELFCRITIC, WHATIS, ARTIFICIAL, ARTIFICIAL_Q, STOP
}
