
public enum ReplyType {
	EXPLAIN, GREETING, REPHRASE, NAMED_GREETING, THANKS, WILL_TELL, NAMED_GOODBYE, ASSURE, ENCOURAGE, GOODBYE, ABORT, COMFORT, TOO_LONG, TOO_SHORT, GO_ON, RIGHT, WRONG, GLAD, REGRET, PROCEED, INSIGHT_R, INSIGHT_W, QUESTION_DEFENSE, YES_NO_RANDOM, REPLY_HATE, REPLY_LOVE, PURPOSE, MEANINGLESS, HOW, WAITING, WORRIED_WAITING, OFFER, GAMBLER, NOGAMBLER, SHOW, OK, CAT, DOG, CITY, GAMES, NOGAMES, VIDEO, NOVIDEO, CLARIFICATION, CONFIDENCE, HOW_SURE, TIME, HINT, EXP, GOOD, HOSPITAL, RIGHTANSWER, UNDERCONFIDENT, OVERCONFIDENT, CALIBRATED, SKIP, WANT_TO_EXPLAIN, OPPORTUNITY_TO_EXPLAIN, ARTIFICIAL_Q, ARTIFICIAL, EXPERT

}
